US-94-TASK-98 UI change for the custom business value attribute
dhruvi1610/SER517-Spring23-team1-AgileMetrics pull request #70
Opened 2023-03-28 08:15 UTC by geethika-n

2023-03-28 08:15 UTC, geethika-n commented
https://tree.taiga.io/project/dhruvimodii-agile-metrics-ser-517/task/98

2023-03-28 15:48 UTC, dhruvi1610 approved these changes

2023-03-30 06:40 UTC, sbaktha1 approved these changes

2023-03-30 19:03 UTC, dhruvi1610 approved these changes

2023-03-30 23:50 UTC, dhruvi1610 requested changes
some conflicts on controllers.js line 4272

2023-03-30 23:58 UTC, merged